language: python

python:
  - 2.7
  - 3.5

cache:
  pip: true
  directories:
    - .tox

sudo: required

env:
  - TOX_ENV=python
  - TOX_ENV=flake8
  - TOX_ENV=structure
  - TOX_ENV=karma
  - TOX_ENV=spelling

matrix:
  exclude:
    - python: 3.5
      env: TOX_ENV=structure
    - python: 3.5
      env: TOX_ENV=karma
    - python: 3.5
      env: TOX_ENV=spelling

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - sudo apt-get install python-enchant -y
  - pip install --upgrade pip
  - pip install tox coveralls sphinxcontrib-spelling
  - pip install codecov

script:
  - tox -e $TOX_ENV

after_success:
  - test $TOX_ENV = "python" && coveralls
  - test $TOX_ENV = "karma" && codecov
