language: python

python:
  - "2.7"

cache:
    pip: true
    directories:
    - .tox

env:
  matrix:
    - TOX_ENV=python
    - TOX_ENV=flake8
    - TOX_ENV=structure

install:
  - pip install tox
  - pip install --upgrade pip
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV

after_success: test $TOX_ENV = "python" && coveralls
