language: python

python:
  - "2.7"

cache:
    pip: true
    directories:
    - .tox

env:
  matrix:
    - TOX_ENV=python
    - TOX_ENV=flake8
    - TOX_ENV=structure

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

install:
  - pip install tox
  - pip install --upgrade pip
  - pip install tox coveralls
  - npm install

script:
  - tox -e $TOX_ENV
  - npm test

after_success: test $TOX_ENV = "python" && coveralls
