# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-07 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'recipes', '0001_initial'), (b'recipes', '0002_auto_20180422_0148'), (b'recipes', '0003_recipe_recipe_type'), (b'recipes', '0004_auto_20180422_1747'), (b'recipes', '0005_auto_20180422_1750'), (b'recipes', '0006_auto_20180422_1756'), (b'recipes', '0007_auto_20180423_0150'), (b'recipes', '0008_auto_20180427_0210'), (b'recipes', '0009_auto_20180427_0215'), (b'recipes', '0010_auto_20180427_0229'), (b'recipes', '0011_auto_20180427_1356'), (b'recipes', '0012_auto_20180502_2124'), (b'recipes', '0013_auto_20180502_2126'), (b'recipes', '0014_auto_20180503_0534'), (b'recipes', '0015_auto_20180503_0538'), (b'recipes', '0016_auto_20180503_0539'), (b'recipes', '0017_auto_20180505_2048'), (b'recipes', '0018_auto_20180507_1928'), (b'recipes', '0019_auto_20180507_1932')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_directions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_string', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The descriptive title for this recipe', max_length=100)),
                ('recipe_type', models.CharField(choices=[('10', 'Unknown'), ('30', 'Entree'), ('40', 'Soup'), ('50', 'Salad'), ('60', 'Drink'), ('70', 'Dessert'), ('80', 'Side Dish'), ('90', 'Sauce/Dressing'), ('100', 'Seasoning')], default='Unknown', help_text='The category for this recipe', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(help_text='A pointer to an existing recipe to link them together', on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='directions',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
        migrations.RenameModel(
            old_name='Directions',
            new_name='Direction',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='raw_string',
            new_name='item_description',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.CharField(choices=[('0', ''), ('10', '\u215b'), ('30', '\t\xbc'), ('40', '\u2153'), ('50', '\xbd'), ('55', '\u2154'), ('57', '\xbe'), ('60', '1'), ('70', '2'), ('80', '3'), ('90', '4'), ('100', '5'), ('110', '6'), ('120', '7'), ('130', '8'), ('140', '9'), ('150', '10')], default='', help_text='The numeric part of the amount of this ingredient', max_length=5),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(choices=[('0', ''), ('5', 'Pinch'), ('10', 'tsp'), ('20', 'Tbsp'), ('30', 'c'), ('40', 'pint'), ('50', 'qt'), ('60', 'liter'), ('70', 'gallon')], default='', help_text='The measurement portion of this ingredient', max_length=25),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='item_description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='A brief nickname for this month, usually auto-generated as YY-MMM', max_length=100)),
                ('month', models.IntegerField(default=1, help_text='The month index (1-12) of this calendar month')),
                ('year', models.IntegerField(default=2018, help_text='The year of this calendar month')),
                ('day01recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 01', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day01recipe0', to='recipes.Recipe')),
                ('day01recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 01', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day01recipe1', to='recipes.Recipe')),
                ('day02recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 02', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day02recipe0', to='recipes.Recipe')),
                ('day02recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 02', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day02recipe1', to='recipes.Recipe')),
                ('day03recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 03', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day03recipe0', to='recipes.Recipe')),
                ('day03recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 03', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day03recipe1', to='recipes.Recipe')),
                ('day04recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 04', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day04recipe0', to='recipes.Recipe')),
                ('day04recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 04', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day04recipe1', to='recipes.Recipe')),
                ('day05recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 05', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day05recipe0', to='recipes.Recipe')),
                ('day05recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 05', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day05recipe1', to='recipes.Recipe')),
                ('day06recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 06', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day06recipe0', to='recipes.Recipe')),
                ('day06recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 06', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day06recipe1', to='recipes.Recipe')),
                ('day07recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 07', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day07recipe0', to='recipes.Recipe')),
                ('day07recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 07', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day07recipe1', to='recipes.Recipe')),
                ('day08recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 08', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day08recipe0', to='recipes.Recipe')),
                ('day08recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 08', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day08recipe1', to='recipes.Recipe')),
                ('day09recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 09', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day09recipe0', to='recipes.Recipe')),
                ('day09recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 09', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day09recipe1', to='recipes.Recipe')),
                ('day10recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 10', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day10recipe0', to='recipes.Recipe')),
                ('day10recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 10', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day10recipe1', to='recipes.Recipe')),
                ('day11recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 11', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day11recipe0', to='recipes.Recipe')),
                ('day11recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 11', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day11recipe1', to='recipes.Recipe')),
                ('day12recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 12', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day12recipe0', to='recipes.Recipe')),
                ('day12recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 12', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day12recipe1', to='recipes.Recipe')),
                ('day13recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 13', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day13recipe0', to='recipes.Recipe')),
                ('day13recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 13', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day13recipe1', to='recipes.Recipe')),
                ('day14recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 14', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day14recipe0', to='recipes.Recipe')),
                ('day14recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 14', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day14recipe1', to='recipes.Recipe')),
                ('day15recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 15', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day15recipe0', to='recipes.Recipe')),
                ('day15recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 15', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day15recipe1', to='recipes.Recipe')),
                ('day16recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 16', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day16recipe0', to='recipes.Recipe')),
                ('day16recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 16', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day16recipe1', to='recipes.Recipe')),
                ('day17recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 17', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day17recipe0', to='recipes.Recipe')),
                ('day17recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 17', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day17recipe1', to='recipes.Recipe')),
                ('day18recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 18', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day18recipe0', to='recipes.Recipe')),
                ('day18recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 18', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day18recipe1', to='recipes.Recipe')),
                ('day19recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 19', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day19recipe0', to='recipes.Recipe')),
                ('day19recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 19', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day19recipe1', to='recipes.Recipe')),
                ('day20recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 20', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day20recipe0', to='recipes.Recipe')),
                ('day20recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 20', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day20recipe1', to='recipes.Recipe')),
                ('day21recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 21', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day21recipe0', to='recipes.Recipe')),
                ('day21recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 21', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day21recipe1', to='recipes.Recipe')),
                ('day22recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 22', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day22recipe0', to='recipes.Recipe')),
                ('day22recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 22', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day22recipe1', to='recipes.Recipe')),
                ('day23recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 23', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day23recipe0', to='recipes.Recipe')),
                ('day23recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 23', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day23recipe1', to='recipes.Recipe')),
                ('day24recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 24', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day24recipe0', to='recipes.Recipe')),
                ('day24recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 24', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day24recipe1', to='recipes.Recipe')),
                ('day25recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 25', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day25recipe0', to='recipes.Recipe')),
                ('day25recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 25', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day25recipe1', to='recipes.Recipe')),
                ('day26recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 26', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day26recipe0', to='recipes.Recipe')),
                ('day26recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 26', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day26recipe1', to='recipes.Recipe')),
                ('day27recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 27', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day27recipe0', to='recipes.Recipe')),
                ('day27recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 27', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day27recipe1', to='recipes.Recipe')),
                ('day28recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 28', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day28recipe0', to='recipes.Recipe')),
                ('day28recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 28', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day28recipe1', to='recipes.Recipe')),
                ('day29recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 29', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day29recipe0', to='recipes.Recipe')),
                ('day29recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 29', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day29recipe1', to='recipes.Recipe')),
                ('day30recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 30', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day30recipe0', to='recipes.Recipe')),
                ('day30recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 30', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day30recipe1', to='recipes.Recipe')),
                ('day31recipe0', models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 31', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day31recipe0', to='recipes.Recipe')),
                ('day31recipe1', models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 31', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day31recipe1', to='recipes.Recipe')),
            ],
        ),
        migrations.AlterField(
            model_name='direction',
            name='full_directions',
            field=models.TextField(help_text='A freeform list of directions for making this recipe'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='recipe',
            field=models.ForeignKey(help_text='A pointer to an existing recipe to link them together', on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='item_description',
            field=models.CharField(blank=True, default='', help_text='A description of this ingredient, Can include amount if the portion does not fit in the prescribed parameters', max_length=200),
        ),
    ]
