# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-07 22:32
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0001_squashed_0019_auto_20180507_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='month',
            field=models.IntegerField(help_text='The month index (1-12) of this calendar month'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='year',
            field=models.IntegerField(help_text='The year of this calendar month'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='recipe',
            field=models.ForeignKey(help_text='A pointer to an existing recipe to link them together', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
    ]
