# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-07 22:38
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0002_auto_20180507_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(help_text='A pointer to an existing recipe to link them together', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
    ]
