# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 14:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_recipe_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='creator',
            field=models.ForeignKey(help_text='The user who created this recipe instance', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
