# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 19:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_calendar_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='full_directions',
            field=models.TextField(help_text='A free-form list of directions for making this recipe'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='recipe',
            field=models.ForeignKey(help_text='A pointer to an existing recipe to link them together', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(help_text='A pointer to an existing recipe to link them together', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='creator',
            field=models.ForeignKey(help_text='The user who created this recipe instance', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
