# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20180509_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='directions',
            field=models.TextField(help_text='A free-form set of text instructions for making this recipe', null=True),
        ),
        migrations.DeleteModel(
            name='Direction',
        ),
    ]
