# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20180427_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='item_description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
