# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20180427_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='A brief nickname for this month, could be just YY-MMM', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='direction',
            name='full_directions',
            field=models.TextField(help_text='A freeform list of directions for making this recipe'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='recipe',
            field=models.ForeignKey(help_text='A pointer to an existing recipe to link them together', on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.CharField(choices=[('0', ''), ('10', '\u215b'), ('30', '\t\xbc'), ('40', '\u2153'), ('50', '\xbd'), ('55', '\u2154'), ('57', '\xbe'), ('60', '1'), ('70', '2'), ('80', '3'), ('90', '4'), ('100', '5'), ('110', '6'), ('120', '7'), ('130', '8'), ('140', '9'), ('150', '10')], default='', help_text='The numeric part of the amount of this ingredient', max_length=5),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='item_description',
            field=models.CharField(blank=True, default='', help_text='A description of this ingredient, Can include amount if the portion does not fit in the prescribed parameters', max_length=200),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(choices=[('0', ''), ('5', 'Pinch'), ('10', 'tsp'), ('20', 'Tbsp'), ('30', 'c'), ('40', 'pint'), ('50', 'qt'), ('60', 'liter'), ('70', 'gallon')], default='', help_text='The measurement portion of this ingredient', max_length=25),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(help_text='A pointer to an existing recipe to link them together', on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('10', 'Unknown'), ('30', 'Entree'), ('40', 'Soup'), ('50', 'Salad'), ('60', 'Drink'), ('70', 'Dessert'), ('80', 'Side Dish'), ('90', 'Sauce/Dressing'), ('100', 'Seasoning')], default='Unknown', help_text='The category for this recipe', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(help_text='The descriptive title for this recipe', max_length=100),
        ),
        migrations.AddField(
            model_name='calendarday',
            name='recipe01',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe01', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendarday',
            name='recipe02',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe02', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendarday',
            name='recipe03',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe03', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendarday',
            name='recipe04',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe04', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day01',
            field=models.OneToOneField(help_text='A pointer to day #01 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day01', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day02',
            field=models.OneToOneField(help_text='A pointer to day #02 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day02', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day03',
            field=models.OneToOneField(help_text='A pointer to day #03 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day03', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day04',
            field=models.OneToOneField(help_text='A pointer to day #04 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day04', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day05',
            field=models.OneToOneField(help_text='A pointer to day #05 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day05', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day06',
            field=models.OneToOneField(help_text='A pointer to day #06 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day06', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day07',
            field=models.OneToOneField(help_text='A pointer to day #07 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day07', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day08',
            field=models.OneToOneField(help_text='A pointer to day #08 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day08', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day09',
            field=models.OneToOneField(help_text='A pointer to day #09 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day09', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day10',
            field=models.OneToOneField(help_text='A pointer to day #10 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day10', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day11',
            field=models.OneToOneField(help_text='A pointer to day #11 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day11', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day12',
            field=models.OneToOneField(help_text='A pointer to day #12 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day12', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day13',
            field=models.OneToOneField(help_text='A pointer to day #13 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day13', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day14',
            field=models.OneToOneField(help_text='A pointer to day #14 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day14', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day15',
            field=models.OneToOneField(help_text='A pointer to day #15 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day15', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day16',
            field=models.OneToOneField(help_text='A pointer to day #16 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day16', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day17',
            field=models.OneToOneField(help_text='A pointer to day #17 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day17', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day18',
            field=models.OneToOneField(help_text='A pointer to day #18 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day18', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day19',
            field=models.OneToOneField(help_text='A pointer to day #19 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day19', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day20',
            field=models.OneToOneField(help_text='A pointer to day #20 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day20', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day21',
            field=models.OneToOneField(help_text='A pointer to day #21 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day21', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day22',
            field=models.OneToOneField(help_text='A pointer to day #22 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day22', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day23',
            field=models.OneToOneField(help_text='A pointer to day #23 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day23', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day24',
            field=models.OneToOneField(help_text='A pointer to day #24 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day24', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day25',
            field=models.OneToOneField(help_text='A pointer to day #25 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day25', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day26',
            field=models.OneToOneField(help_text='A pointer to day #26 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day26', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day27',
            field=models.OneToOneField(help_text='A pointer to day #27 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day27', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day28',
            field=models.OneToOneField(help_text='A pointer to day #28 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day28', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day29',
            field=models.OneToOneField(help_text='A pointer to day #29 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day29', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day30',
            field=models.OneToOneField(help_text='A pointer to day #30 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day30', to='recipes.CalendarDay'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day31',
            field=models.OneToOneField(help_text='A pointer to day #31 of this month', on_delete=django.db.models.deletion.CASCADE, related_name='day31', to='recipes.CalendarDay'),
        ),
    ]
