# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-30 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20180517_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='images/%y/%m/%d'),
        ),
    ]
