# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0012_auto_20180502_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarday',
            name='nickname',
            field=models.CharField(default=None,
                                   help_text='A brief nickname for this month, usually auto-generated as YY-MMM-DD',
                                   max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendar',
            name='nickname',
            field=models.CharField(help_text='A brief nickname for this month, usually auto-generated as YY-MMM',
                                   max_length=100),
        ),
    ]
