# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-30 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20180531_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('10', 'Unknown'), ('30', 'Entree'), ('35', 'Salad-Entree'), ('40', 'Soup'), ('50', 'Salad'), ('60', 'Drink'), ('70', 'Dessert'), ('80', 'Side Dish'), ('90', 'Sauce/Dressing'), ('100', 'Seasoning')], default='Unknown', help_text='The category for this recipe', max_length=20),
        ),
    ]
