# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0013_auto_20180502_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='month',
            field=models.IntegerField(default=1, help_text='The month index (1-12) of this calendar month'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendar',
            name='year',
            field=models.IntegerField(default=2018, help_text='The year of this calendar month'),
            preserve_default=False,
        ),
    ]
