# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-07 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20180505_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarday',
            name='recipe01',
        ),
        migrations.RemoveField(
            model_name='calendarday',
            name='recipe02',
        ),
        migrations.RemoveField(
            model_name='calendarday',
            name='recipe03',
        ),
        migrations.RemoveField(
            model_name='calendarday',
            name='recipe04',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day01',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day02',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day03',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day04',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day05',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day06',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day07',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day08',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day09',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day10',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day11',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day12',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day13',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day14',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day15',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day16',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day17',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day18',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day19',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day20',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day21',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day22',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day23',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day24',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day25',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day26',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day27',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day28',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day29',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day30',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day31',
        ),
        migrations.AddField(
            model_name='calendar',
            name='day00recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 00', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day00recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day00recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 00', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day00recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day01recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 01', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day01recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day01recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 01', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day01recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day02recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 02', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day02recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day02recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 02', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day02recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day03recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 03', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day03recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day03recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 03', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day03recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day04recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 04', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day04recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day04recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 04', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day04recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day05recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 05', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day05recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day05recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 05', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day05recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day06recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 06', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day06recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day06recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 06', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day06recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day07recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 07', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day07recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day07recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 07', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day07recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day08recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 08', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day08recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day08recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 08', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day08recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day09recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 09', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day09recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day09recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 09', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day09recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day10recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 10', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day10recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day10recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 10', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day10recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day11recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 11', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day11recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day11recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 11', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day11recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day12recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 12', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day12recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day12recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 12', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day12recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day13recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 13', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day13recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day13recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 13', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day13recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day14recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 14', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day14recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day14recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 14', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day14recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day15recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 15', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day15recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day15recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 15', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day15recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day16recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 16', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day16recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day16recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 16', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day16recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day17recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 17', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day17recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day17recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 17', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day17recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day18recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 18', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day18recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day18recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 18', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day18recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day19recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 19', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day19recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day19recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 19', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day19recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day20recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 20', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day20recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day20recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 20', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day20recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day21recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 21', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day21recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day21recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 21', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day21recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day22recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 22', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day22recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day22recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 22', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day22recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day23recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 23', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day23recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day23recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 23', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day23recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day24recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 24', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day24recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day24recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 24', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day24recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day25recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 25', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day25recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day25recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 25', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day25recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day26recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 26', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day26recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day26recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 26', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day26recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day27recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 27', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day27recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day27recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 27', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day27recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day28recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 28', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day28recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day28recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 28', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day28recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day29recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 29', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day29recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day29recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 29', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day29recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day30recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 30', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day30recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day30recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 30', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day30recipe1', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day31recipe0',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 0 for day 31', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day31recipe0', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='day31recipe1',
            field=models.ForeignKey(blank=True, help_text='A pointer to recipe 1 for day 31', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day31recipe1', to='recipes.Recipe'),
        ),
        migrations.DeleteModel(
            name='CalendarDay',
        ),
    ]
